### ISSUE TITLE
Some personal to-do reminders.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#105]
**Some personal to-do reminders (unrelated to any of the other issues).**
_This list isn't static; Entries may be added and/or removed without notice._
- [x] (v1.0.0) Update `CONTRIBUTING.md` (_this is kind of old, and could be written better_).
- [x] (v1.0.0) Update `PEOPLE.md` (_currently still using the original text written back in February with the work-in-progress notice_).
- <strike>Update the donations message listed on the webpage (_currently still mentions that no donations have been received to-date; two donations have been made since that was written; something should be done there and the text rewritten_).</strike>
- [x] (v1.0.0) Update CHMOD recommendations included in the READMEs (refer #104).
---
*Migrated from `todo` items previously mentioned within docblock comments.*
- [x] (v1.0.0) Improve URL scanner regex (terminating characters sometimes aren't found and URLs fail to be caught).

**Comment by Maikuolan** [comment]
*Donations item struck from list (donations button doesn't exist anymore anyway, and I'm not sure whether I'll ever bring it back again; might seek alternative arrangements in the future maybe, but I could foresee potential problems in the future with how it had been set up before; not worth actively encouraging this, in any case).*
