### ISSUE TITLE
Front-end system to-do list

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#110]
**Front-end system to-do list**
_An issue for tracking progress made towards the front-end system for phpMussel. Items will be added as they become relevant and marked off upon completion._
- [x] Alpha stage: Coming up with some new plans, ideas, etc; Syncing some initial commits (getting the bare bones of the front-end system working).
- [x] Beta stage: Fleshing it out a bit more; Trying to implement some of our plans, ideas, etc (the front-end system mightn't be completed, but should be at least more functional by this stage; this item should only be marked as completed upon thorough testing of all changes to ensure that everything is working as intended).
- [x] Configuration update.
- [x] Documentation update.
- [x] Access/login/sessions system.
- [x] Deprecate and remove the "browser controls" feature (browser controls will be superseded by the front-end system).
- [x] Building a front-end updates manager.
- [x] Building a front-end configuration manager.

**Comment by Maikuolan** [comment]
*Completed: Documentation update.*

**Comment by Maikuolan** [comment]
*Completed: Beta stage.*
*Completed: Configuration update.*

**Comment by Maikuolan** [comment]
*Scratching installer off the to-do list and marking issue as implemented. See: https://github.com/Maikuolan/CIDRAM/issues/27*
