### ISSUE TITLE
[Checklist] SensioLabs QA

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#125]
*Current score: <strike>40/100</strike> <strike>87/100</strike> 100/100. Target score: 100/100.*
- [x] Goal: Bronze medal.
- [x] Goal: Silver medal.
- [x] Goal: Gold medal.
- [x] Goal: Platinum medal (100/100).

**Comment by DanielRuf** [comment]
About the logging todo: we could also integrate [monolog](https://github.com/Seldaek/monolog) as composer package. Less work with rewriting some logging feature ;-)

@ error compression to try / catch block

**Comment by Maikuolan** [comment]
Definitely; Will get onto this. :-)

**Comment by Maikuolan** [comment]
Currently at *65/100*. I'll need to rework how plugin hooks are handled, I think; As soon as that's done, the code duplication errors should hopefully be resolved, which should get it to silver, at least. Also need to figure out what'll be done about some of the `ini_get()`/`ini_set()` calls; That's the other big one that SensioLabs is flagging. The big problem though, is that when some of those calls are removed, and we rely on the default settings normally included with most PHP configurations as per standard, then often, PHP just crashes when running phpMussel, due to PCRE backticking itself to death and such. Might be able to resolve this when an automated tool for cutting new signature sets has been developed; If the tool is written in such a way as to avoid problematic patterns, it might work out alright. We'll see, I guess.

**Comment by Maikuolan** [comment]
`ini_get()`/`ini_set()` calls removed. Silver medal reached.

**Comment by DanielRuf** [comment]
Awesome =)

**Comment by Maikuolan** [comment]
To get from the current 95/100 score to the desired 100/100 score, the way that plugin hooks work is going to need to be reworked (due to that each hook currently occupies 28 lines of code, which is perceived as duplicated code by SensioLabs QA).

I could reduce that down to 1 line of code per hook (and thus reach the desired score) by using a separate executor closure to cycle through and execute all the registered closures and functions within its own scope, or down to about 3 lines per hook by cycling through and executing all the registered closures and functions for each hook and just pulling them via closure factory or something like that if I wanted to maintain being able to execute within the same scope as the hooks themselves; Either way, not too difficult and not really a big deal.

The problem, however, is that the main reason that the current code for each hook occupies 28 lines of code is due to the ability/need to cycle through some predefined list of variables to parse into the registered closure/function and then return them back to the calling scope (corresponds to "parameter 3" mentioned by the v1 boilerplate). Currently, all of the plugins which already exist for phpMussel (only 4 currently AFAIK; also all listed on the README for the v1 boilerplate) don't use this parameter 3 anyhow, and so, if I was to ditch it completely, it wouldn't cause any backwards-compatibility issues for any of the already existent phpMussel plugins, but ditching it would nonetheless technically introduce a backwards-incompatibility with the plugin system and as per is documented by the v1 boilerplate currently (and so, I would need to modify the plugin system documentation included with the v1 boilerplate, remove any mention of parameter 3, etc), and also would mean that scope-specific variables couldn't be parsed between scopes via the plugin system anymore.

Of course, in case any scope-specific variables were actually needed by some plugin at some point in the future, the above-mentioned issue could be resolved simply by modifying the needed variables as so that they aren't scope-specific anymore (for example, like renaming some `$Foo` variable from within some closure from that to `$phpMussel['Foo']` and such).

Anyhow, all of this would only be 15 minutes or so of work to implement, so it's not anything time costly, but due to that it would involve a backwards-incompatible change to the plugins system, I would like to know your opinions about this before doing anything, if possible. @DanielRuf @nhlm 

(Conversely, if I don't rework the hooks, then I don't currently see any viable way to eliminate this perceived code duplication otherwise).

**Comment by Maikuolan** [comment]
Platinum medal reached. Closing. :-)
