### ISSUE TITLE
List of goals, suggestions and ideas for future releases.

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#140]
**List of goals, suggestions and ideas for future releases.**
_This list isn't static; Entries may be added and/or removed without notice. Listed order does not represent priority. List is not comprehensive (issues may exist that aren't listed)._

- [x] v1.1.0: Metadata cleanup routine *(Implemented 2017.10.07)*.
- [x] v1.1.0: Ability to fetch extended descriptions from L10N data *(Implemented 2017.10.09)*.
- [x] v1.1.0: Add statistics page to the front-end *(Implemented 2017.10.09)*.
- [x] v1.1.0: Add quarantine page to the front-end *(Implemented 2017.10.16)*.
- [x] v1.1.0: CI reports/tests on the front-end updates page *(Implemented 2017.10.26)*.
- [x] v1.1.0: Split out front-end closures from the main functions file *(Implemented 2017.10.26)*.
- [x] v1.1.0: Remove PHP < 5.4.0 syntax *(Implemented 2017.10.27)*.
- [x] v1.1.0: Prepare Cronable API *(Implemented 2017.10.28)*.
- [x] v1.5.0: Improve support for macros (see: #106) *(Implemented 2018.07.31)*.
- [x] v1.6.0: 2FA (Two-Factor Authentication) *(Implemented 2018.08.12)*.
- [x] v1.7.0: Add recursion support for ZIP scanning (see: #2) *(Implemented 2018.10.17)*.
- [x] v1.7.0: Add RAR support (see: #2) *(Implemented 2018.10.17)*.
- [x] v1.8.0: Add Crx support (see: #2) *(Implemented 2018.12.12)*.
- [x] v1.11.0, v2.0.0: Implement mechanisms for platform contingencies/redundancies *(Implemented 2019.05.31)*.
- [x] v1.11.0, v2.0.0: Remotes redirect for handling updates when primary update sources are unavailable *(Implemented 2019.05.31)*.

**Comment by DanielRuf** [comment]
> Improve unit tests.

We have unit tests?

**Comment by Maikuolan** [comment]
> We have unit tests?

Not really. '^^

There's a Travis CI in the repo to run PHPUnit after each commit, and one "test" included, which only fails if attempting to run the package results in actual PHP errors (or alternatively, in a worst-case scenario, if the entire thing crashes):

```PHP
class Experimental extends \PHPUnit_Framework_TestCase
{
    public function testErrors() {
        $this->assertNull(error_get_last(), 'Errors were reported.');
    }
}
```

..And so, technically, it could be justified - by a stretch - that we we "have tests". However, seeing as we don't actually really have tests, we definitely need to "improve unit tests". :P 

(In other words: The first step towards writing proper unit tests - of connecting the repo with Travis CI and getting it to run PHPUnit on each commit - has been taken, but the actual tests themselves haven't been written yet. The one test that exists currently, which isn't much of a "unit" test anyhow due to that it's testing against the whole rather than against any one specific unit, exists because it's better than having nothing, but once actual proper "unit" tests are written, it will become superfluous and could be ditched anyhow, seeing as if PHP starts producing errors or crashing, I imagine that most/all other tests would fail anyhow).

**Comment by Maikuolan** [comment]
*List updated due to #173.*

**Comment by Maikuolan** [comment]
Removing all remaining to-do items from this list so that we can close this issue. (Too many stale issues around; Not enough time).

> Work through all issues mentioned at [phpMussel/universe](https://github.com/phpMussel/universe/issues).

Entirely valid, but each relevant issue already exists in its own right, so.. listing it here is duplication anyway.

> Improve data decoding/normalisation procedures.

I'll just create a new, separate issue for this.

> Add 7z support (see: #2).

Duplicate via *"see: ..."*.

> Automate URL scanner updates (SigTool implementation preferable).

I can create a new issue over there at the SigTool repository.

> Work through plugin system ideas (see: #23).

Duplicate via *"see: ..."*.

> Implemented Virus Total back-reporting and file submissions mechanism (see: #12).

Duplicate via *"see: ..."*.

Marking as *implemented* (due to the already completed to-do items) and closing.
