### ISSUE TITLE
phpMussel v1.0.0 Transitional Preparations Checklist

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/phpMussel#82]
**phpMussel v1.0.0 Transitional Preparations Checklist.**

_Entries will be marked upon being completed and committed to the master codebase._

_This is not a static list: New items may be added as new needs are determined._
- [x] Mark/indicate all deprecated functions in the core code to be removed by the next major version release (1.0.0).
- [x] Complete all necessary PSR work, in order to improve coding standards, improve code quality and to assist the development team in making all necessary changes for the next major version release. _Refer: https://github.com/Maikuolan/phpMussel/issues/80_
- [x] Complete all necessary phpDoc work, in order to improve documentation and to assist the development team in making all necessary changes for the next major version release.
- [x] Address all currently known bugs, to determine if they'll be fixable prior to the next major version release; Attempt to fix all known fixable bugs; Ensure no known bugs (especially known non-fixable bugs) will be capable of snowballing the next major version release.

**Comment by Maikuolan** [comment]
*Feature introduced with #28 contained a bug which hasn't yet been fixed, but the feature itself has been mothballed for the moment, and so, said bug definitely won't "snowball", in any case (issue remains open as I hope to be able to eventually reinstate the feature, minus the bug). There's an obscure bug identified with #61 that has since been marked as "Won't Fix", and isn't a problem anymore since PHP 7.1.0 anyhow (issue has been closed). That aside, all __known__ bugs have been fully addressed (can't account for the unknown, of course), so technically, the final item in this list, "Address all currently known bugs", can be marked off.*
